# Generated by Django 3.1.3 on 2021-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FilePathField(default='', path='/home/thoughtwin/projects/virtual_folio_django/myportfolio/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='/home/thoughtwin/projects/virtual_folio_django/myportfolio/static/img'),
        ),
    ]
