# Generated by Django 3.1.3 on 2021-08-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_auto_20210805_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
