# Generated by Django 3.2.6 on 2021-08-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_auto_20210816_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
