# Generated by Django 3.2.6 on 2021-08-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_demo_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo_profile',
            new_name='DemoProfile',
        ),
    ]
