# Generated by Django 3.2.6 on 2021-08-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_rename_demo_profile_demoprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoProfile',
        ),
    ]
